org: rolandodiaz
service: api-web-scraping

provider:
  name: aws
  runtime: python3.12
  memorySize: 1024     # Reducido ya que no necesitamos tanto como con Selenium
  timeout: 120        # Aumentado para dar tiempo a ScrapingBee
  iam:
    role: arn:aws:iam::409362080365:role/LabRole
  environment:
    SCRAPINGBEE_API_KEY: XI2EJYTI4PNGLQVKRJ6FL30GXOEZ4JIV7MGN8E6AK30CFUUQUEHXFWASE58CF80MX22AQOYZJTSBVAV7

functions:
  scrape_table:
    handler: scrap_table.lambda_handler
    package:
      include:
        - ./**
    events:
      - http:
          path: /scrape/table
          method: get
          cors: true
          integration: lambda

resources:
  Resources:
    TablaWebScrapping:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TablaWebScrapping
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
