org: rolandodiaz
service: api-web-scraping

provider:
  name: aws
  runtime: python3.12
  memorySize: 2048  # Aumentado para Selenium
  timeout: 60       # Aumentado para scraping dinámico
  iam:
    role: arn:aws:iam::409362080365:role/LabRole
  environment:
    CHROME_BINARY: /opt/chrome/chrome
    CHROMEDRIVER_PATH: /opt/chromedriver

functions:
  scrape_table:
    handler: scrap_table.lambda_handler
    layers:
      # Layer de Chrome para AWS Lambda (ajusta la versión según tu región)
      - arn:aws:lambda:us-east-1:764866452798:layer:chrome-aws-lambda:31
    package:
      include:
        - ./**
    events:
      - http:
          path: /scrape/table
          method: get
          cors: true
          integration: lambda

resources:
  Resources:
    TablaWebScrapping:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TablaWebScrapping
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
